### ISSUE TITLE
Flag to reuse virtual env for py3

### ISSUE THREAD

**Issue by ludoch** [NoCommandLine/dev_appserver-python3-windows#1]
The readme mentions a Flag to reuse virtual env for py3, but it was done 2 weeks ago in the gcloud devappserver, so no need to do it anymore here.

For the other path, I am studying it to see what we can do. Thanks!

**Comment by NoCommandLine** [comment]
> The readme mentions a Flag to reuse virtual env for py3, but it was done 2 weeks ago in the gcloud devappserver

You're right. It's on the 'to do' list to update the ```read me```  to say this has been done.

**Comment by NoCommandLine** [comment]
```README``` has been updated.
