### ISSUE TITLE
Fail run on windows using SDK 470.0.0 with pyhton 39

### ISSUE THREAD

**Issue by mavalarbe** [NoCommandLine/dev_appserver-python3-windows#3]
From CMD i'm trying this:
1. Install Python39 con Path C:\python39 (Version 3.9.13)
2. Install Python39 con Path C:\python27 (Version 2.7.18)
3. Install Google SDK with version Google Cloud SDK 470.0.0, app-engine-python 1.9.111
4. Download your copy of the file from the 'src' folder and overwrite the original file
5. Set CLOUDSDK_DEVAPPSERVER_PYTHON  with python 2 Path, using set CLOUDSDK_DEVAPPSERVER_PYTHON=C:\Python27\python.exe
6. try run dev_appserver usign a simple hello_world example, using dev_appserver.py app.yaml

When i tried this its generate the next exception:

Traceback (most recent call last):
  File "C:\CloudSDK\google-cloud-sdk\bin\dev_appserver.py", line 13, in <module>
    from bootstrapping import bootstrapping
  File "C:\CloudSDK\google-cloud-sdk\bin\bootstrapping\bootstrapping.py", line 24, in <module>
    from . import setup  # pylint:disable=g-import-not-at-top
  File "C:\CloudSDK\google-cloud-sdk\bin\bootstrapping\setup.py", line 57, in <module>
    from googlecloudsdk.core.util import platforms
  File "C:\CloudSDK\google-cloud-sdk\lib\googlecloudsdk\__init__.py", line 23, in <module>
    import importlib.util
ImportError: No module named util

I Searched this and found that it's cause the version of python, but i'm not sure how to deal with that, can someone help me?

**Comment by NoCommandLine** [comment]
Hi,

Some breaking changes have been introduced into the newer versions of `gcloud SDK`. I'm yet to upgrade the patch to work with these newer versions (currently working on it, & hope to get it done in April).

I have `gcloud SDK v429.0.0` on my windows machine and the patch works on it. I think someone said they're on `v431.0.0` and it works for them (see [this](https://www.googlecloudcommunity.com/gc/Serverless/Has-anyone-tried-the-new-App-Engine-dev-appserver-for-Python-3/m-p/727653#M3447)).

So, you can either wait for the updated patch or downgrade to one of the mentioned gcloud SDK versions.

**Comment by NoCommandLine** [comment]
A new version of the patch to support `gcloud SDK v470.0.0` is now available [here](https://github.com/NoCommandLine/dev_appserver-python3-windows/tree/main/src/gcloud_sdk_470.0.0%2B).

There is a known [issue](https://github.com/NoCommandLine/dev_appserver-python3-windows/issues/4) with the `-python_virtualenv_path` flag. When you use the flag, it gives an error on subsequent runs of your App (there's a permission denied error on the specified `-python_virtualenv_path`). The solution for now is to not use the flag until I come up with a fix for it.
